// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xoltawn/simple-file-storage-file-service/domain (interfaces: FileUsecase)

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/xoltawn/simple-file-storage-file-service/domain"
)

// MockFileUsecase is a mock of FileUsecase interface.
type MockFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFileUsecaseMockRecorder
}

// MockFileUsecaseMockRecorder is the mock recorder for MockFileUsecase.
type MockFileUsecaseMockRecorder struct {
	mock *MockFileUsecase
}

// NewMockFileUsecase creates a new mock instance.
func NewMockFileUsecase(ctrl *gomock.Controller) *MockFileUsecase {
	mock := &MockFileUsecase{ctrl: ctrl}
	mock.recorder = &MockFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUsecase) EXPECT() *MockFileUsecaseMockRecorder {
	return m.recorder
}

// FetchFiles mocks base method.
func (m *MockFileUsecase) FetchFiles(arg0 context.Context, arg1, arg2 int) ([]domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFiles", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFiles indicates an expected call of FetchFiles.
func (mr *MockFileUsecaseMockRecorder) FetchFiles(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFiles", reflect.TypeOf((*MockFileUsecase)(nil).FetchFiles), arg0, arg1, arg2)
}

// SaveFile mocks base method.
func (m *MockFileUsecase) SaveFile(arg0 context.Context, arg1 []byte, arg2 *domain.File, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockFileUsecaseMockRecorder) SaveFile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockFileUsecase)(nil).SaveFile), arg0, arg1, arg2, arg3)
}

// SaveMutltipleFiles mocks base method.
func (m *MockFileUsecase) SaveMutltipleFiles(arg0 context.Context, arg1 []*domain.FileWithBytes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMutltipleFiles", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMutltipleFiles indicates an expected call of SaveMutltipleFiles.
func (mr *MockFileUsecaseMockRecorder) SaveMutltipleFiles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMutltipleFiles", reflect.TypeOf((*MockFileUsecase)(nil).SaveMutltipleFiles), arg0, arg1)
}
