version: '3.8'

services:
  pg-0:
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      - "REPMGR_PARTNER_NODES=${REPMGR_PARTNER_NODES}"
      - "REPMGR_NODE_NAME=${REPMGR_NODE_NAME}"
      - "REPMGR_NODE_NETWORK_NAME=${REPMGR_NODE_NETWORK_NAME}"
      - "REPMGR_PRIMARY_HOST=${REPMGR_PRIMARY_HOST}"
      - "REPMGR_PASSWORD=${REPMGR_PASSWORD}"
      - "POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}"
    image: 'registry.docker.ir/bitnami/postgresql-repmgr:15'

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks: 
  #     - simple-file-storage

networks:
  simple-file-storage:
    name: simple-file-storage
    external: true    